
version: "3.7"

services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'A1234'
      MYSQL_DATABASE: 'chatdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"
volumes:
  mysql-data:
